spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  liquibase:
    enabled: true
    default-schema: EKO
    database-change-log-table: RIG_DATABASECHANGELOG
    database-change-log-lock-table: RIG_DATABASECHANGELOGLOCK
    contexts: ${spring.profiles}
    change-log: classpath:/db/changelog/db.changelog-master.xml
---
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: default
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    properties:
      hibernate:
        default_schema: EKO
    hibernate:
      ddl-auto: none
      javax:
        persistence:
          lock:
            timeout: 15000 #WORKS!
  datasource:
    hikari:
      maximum-pool-size: 10
    url: jdbc:h2:mem:testdb;INIT=CREATE SCHEMA IF NOT EXISTS EKO;
    username: sa
    password:
    driver:
      class-name: org.h2.Driver
  sql:
    init:
      mode: always